Repository JandenMa/pglink-lite, pull requests merged in 2019-09, with the labels that each got.

#8 Auto Set Time Fields
  README.md
  index.d.ts
  index.js
  lib/core/dataAccess.js
  lib/model/index.d.ts
  lib/model/index.js
  package.json
Labels: Optimization, documentation

#10 v0.1.9
  LICENCE
  README.md
  lib/core/dataAccess.d.ts
  lib/core/dataAccess.js
Labels: Optimization, bug fixes, documentation

#12 Fixed check columns function
  lib/core/dataAccess.js
Labels: bug fixes
